# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from addpaneldialog import Ui_dialog as Form

import imp
time = imp.load_source('time', './time.py')
from time import Ui_Dialog as Time

import models
import pandas as pd


class TableModel(QtCore.QAbstractTableModel):

    def __init__(self, data):
        super(TableModel, self).__init__()
        self._data = data

    def data(self, index, role):
        if role == QtCore.Qt.DisplayRole:
            value = self._data.iloc[index.row(), index.column()]
            return str(value)
    def rowCount(self, index):
        return self._data.shape[0]

    def columnCount(self, index):
        return self._data.shape[1]

    def headerData(self, section, orientation, role):
        # section is the index of the column/row.
        if role == QtCore.Qt.DisplayRole:
            if orientation == QtCore.Qt.Horizontal:
                return str(self._data.columns[section])



class Ui_MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        models.startDatabase()
        self._dataBase = models.BaseModel
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)




        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.table = QtWidgets.QTableView()
        data = pd.DataFrame(self._dataBase.panels(), columns=['№', 'Название панели', 'Описание'], )
        self.model = TableModel(data)
        self.table.setModel(self.model)
        self.verticalLayout_2.addWidget(self.table)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.new_time_panel_action = QtWidgets.QAction(self)
        self.new_time_panel_action.setCheckable(True)
        self.new_time_panel_action.setObjectName("new_time_panel_action")
        self.setCentralWidget(self.centralwidget)
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.func_mappingSignal()
        self.pushButton.clicked.connect(self.add_time_panel)

    def func_mappingSignal(self):
        self.table.clicked.connect(self.add)


    def updateTable(self):
        data = pd.DataFrame(self._dataBase.panels(), columns=['№', 'Название панели', 'Описание'], )
        self.model = TableModel(data)
        self.table.setModel(self.model)

    def add_time_panel(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = Form()
        dialog.ui.setupUi(dialog)
        dialog.show()
        dialog.exec_()
        self.updateTable()

    def add(self, item):
        if (type(item) == bool):
            return

        item = self.model.index(item.row(), 1)
        sf = item.data()
        dialog = QtWidgets.QDialog()
        dialog.ui = Time()
        dialog.ui.setupUi(dialog)
        dialog.ui.showTimer(sf)
        dialog.show()
        dialog.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Добавить панель времени"))
        self.label.setText(_translate("MainWindow", "Выберите панель времени"))
        header = self.table.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.new_time_panel_action.setText(_translate("MainWindow", "Добавить панель времени"))




