# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'time.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QLabel, QInputDialog, QLineEdit, QSpinBox

import clock
from models import *


def getTime():
    hours = QInputDialog.getInt(None, "Часы", "Введите часы:", 0, 0, 23, 1)
    if hours[1]:
        minutes = QInputDialog.getInt(None, "Минуты", "Введите минуты:", 0, 0, 59, 1)
        if minutes[1]:
            seconds = QInputDialog.getInt(None, "Секунды", "Введите секунды:", 0, 0, 59, 1)
            if seconds[1]:
                return hours[0], minutes[0], seconds[0]
    return None


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(626, 504)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(540, 470, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 501, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vert = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vert.setContentsMargins(0, 0, 0, 0)
        self.vert.setObjectName("vert")

        self.pushButton.clicked.connect(self.addTimer)
        self.retranslateUi(Dialog)


        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def showTimer(self, panelName):
        self.panel = BaseModel.getPanelByPanelName(panelName)
        self.dialog.setWindowTitle("Панель времени " + panelName)
        d = BaseModel.getClockFaceByPanelName(panelName)
        for i in range(len(d)):
            lab = QLabel(d[i][0])
            self.vert.addWidget(lab)
            cl = clock.Clock(d[i][1], d[i][2])
            self.vert.addWidget(cl)


    def addTimer(self):
        name = QInputDialog.getText(None, "Новый циферблат", "Введите название:", QLineEdit.Normal)
        if name[1]:
            utc = QInputDialog.getInt(None, "Часовой пояс", "Введите часовой пояс:", 0, -12, 12, 1)
            if utc[1]:
                mode, ok = QInputDialog.getItem(None, "Режим", "Введите режим работы:", ["Обычный", "Обратный отсчёт"], 0, False)
                if ok:
                    if mode == "Обратный отсчёт":
                        _time = getTime()
                        if _time is not None:
                            hours, minutes, seconds = _time
                        else:
                            return
                    res = (mode == "Обычный")

                    name_timer = QLabel(name[0])
                    self.vert.addWidget(name_timer)

                    mode = 1 if mode == "Обычный" else 2
                    if mode == 1:
                        BaseModel.createClockFace(name[0], mode, utc[0], self.panel)

                        cl = clock.Clock(utc[0], res)
                        self.vert.addWidget(cl)
                    elif mode == 2:

                        current_date_time = datetime.datetime.now()
                        BaseModel.createClockFace(name[0], mode, utc[0], self.panel,
                                                  current_date_time, current_date_time +
                                                  datetime.timedelta(hours=hours, minutes=minutes, seconds=seconds))

                        cl = clock.Clock(None, res, hours, minutes, seconds)
                        self.vert.addWidget(cl)




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Панель времени"))
        self.pushButton.setText(_translate("Dialog", "Добавить"))


